# Set CLICOLOR if you want Ansi Colors in iTerm2 
export CLICOLOR=1

# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color

set -o vi #setting the vi mode
#===============
# ALIASES
#===============
alias ls='ls -G'


