# Set CLICOLOR if you want Ansi Colors in iTerm2 
export CLICOLOR=1

# Set colors to match iTerm2 Terminal Colors
export TERM=xterm-256color

set -o vi #setting the vi mode
export PS1="[ \u: \w ] \n >> "

export WORKON_HOME=/Users/asood/code/python_virtualenvs
source /usr/local/bin/virtualenvwrapper.sh #Invoke virtual env
#===============
# ALIASES
#===============
# -- GENERIC
alias ls='ls -G'
alias tig='tig status'

alias ..='cd ..'         # Go up one directory
alias ...='cd ../..'     # Go up two directories
alias ....='cd ../../..' # Go up three directories

alias md='mkdir -p'
alias rd='rmdir'

#custom directories
alias code='cd ~/code'

# Get rid of those pesky .DS_Store files recursively
alias dsclean='find . -type f -name .DS_Store -print0 | xargs -0 rm'

# -- MAVEN
alias mci='mvn clean install'
alias mi='mvn install'
alias mc='mvn clean'
alias mcisk='mci -Dmaven.test.skip=true'
